name: junta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_messaging: ^15.2.9
  firebase_storage: ^12.4.9
  go_router: ^16.0.0
  flutter_riverpod: ^2.6.1
  permission_handler: ^12.0.1
  fast_contacts: ^4.0.0
  uuid: ^4.5.1
  intl: ^0.20.2
  firebase_database: ^11.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
